theme: jekyll-theme-architect
url: https://avivfaraj.github.io/cv/
description: Data Science Graduate Student <br> at Drexel University <br> [LinkedIn](https://www.linkedin.com/in/aviv-faraj-857278180/) | [Email](mailto:avivfaraj4@gmail.com) | [GitHub](https://github.com/avivfaraj)
title: Aviv Faraj
